In [1]:
import pandas as pd
import os, sys
from os.path import join

In [2]:
데이터경로 = '../data'

## 엑셀 파일 읽기

In [3]:
프레임목록 = {}
for 시즌 in range(2013, 2016):
    프레임 = pd.read_excel(join(데이터경로, 'NC Dinos {}.xlsx').format(시즌))
    프레임목록[시즌] = 프레임

여러 개의 시트가 담긴 경우

sheetname=

기본: 첫 번째 시트만

In [4]:
NC시즌 = pd.read_excel(join(데이터경로, 'NC Dinos.xlsx'), sheetname=None)

In [5]:
NC시즌

{'2013':     선수명  팀명   경기   타석   타수   안타  홈런  득점  타점  볼넷   삼진  도루  BABIP     타율    출루율  \
 0   모창민  NC  108  436  395  109  12  57  51  37   68  16  0.307  0.276  0.339
 1   이호준  NC  126  508  442  123  20  46  87  60  109   2  0.324  0.278  0.362
 2   김종호  NC  128  546  465  129   0  72  22  57  100  50  0.352  0.277  0.376
 3   나성범  NC  104  458  404   98  14  55  64  33   95  12  0.279  0.243  0.319
 4   조영훈  NC  120  426  380  107   6  38  39  39   56   4  0.316  0.282  0.350
 5   이현곤  NC   91  161  139   38   0  10   9  16   14   2  0.304  0.273  0.361
 6   이상호  NC  102  138  125   31   0  26  13   9   21  24  0.298  0.248  0.299
 7   강진성  NC    3    3    2    1   0   1   0   1    0   0  0.500  0.500  0.667
 8   조평호  NC   26   86   79   21   2  12   7   6   24   1  0.358  0.266  0.318
 9   박민우  NC   32   48   42   11   0  10   6   5    7   9  0.306  0.262  0.333
 10  박정준  NC   77  195  167   41   4  24  21  23   44   4  0.303  0.246  0.335
 11  이승호  NC    2    1    0    0   0   0   0   1    0   1      -      -  1.000
 12  마낙길  NC   24   31   29    9   0   5   0   1    5   2  0.375  0.310  0.333
 13  김성욱  NC    4    4    4    1   0   0   1   0    2   0  0.500  0.250  0.250
 14  강구성  NC    2    2    2    0   0   0   0   0    0   0  0.000  0.000  0.000
 15  지석훈  NC  104  356  309   68   3  25  35  30   82   2  0.285  0.220  0.300
 16  김종찬  NC    5    7    7    1   0   0   0   0    3   0  0.250  0.143  0.143
 17  차화준  NC   58  121  106   24   1  18   7  12   29   4  0.295  0.226  0.306
 18  김동건  NC    7   17   16    2   1   1   1   1    7   0  0.125  0.125  0.176
 19  이창섭  NC    5    5    5    0   0   0   0   0    2   0  0.000  0.000  0.000

       장타율    OPS   wOBA   WAR
 0   0.443  0.782  0.353  2.31
 1   0.475  0.837  0.373  1.85
 2   0.333  0.709  0.339  1.55
 3   0.416  0.735  0.329  1.50
 4   0.413  0.763  0.348  0.83
 5   0.324  0.685  0.327  0.52
 6   0.320  0.619  0.289  0.16
 7   1.000  1.667  0.671  0.10
 8   0.418  0.736  0.329  0.09
 9   0.286  0.619  0.296  0.07
 10  0.353  0.688  0.320  0.06
 11      -      -  0.712  0.06
 12  0.345  0.678  0.317 -0.03
 13  0.250  0.500  0.234 -0.03
 14  0.000  0.000  0.000 -0.06
 15  0.330  0.630  0.293 -0.09
 16  0.143  0.286  0.134 -0.11
 17  0.311  0.617  0.289 -0.12
 18  0.313  0.489  0.216 -0.14
 19  0.000  0.000  0.000 -0.14  ,
 '2014':      선수명  팀명   경기   타석   타수   안타  홈런  득점   타점  볼넷   삼진  도루  BABIP     타율  \
 0    테임즈  NC  125  514  443  152  37  95  121  58   99  11  0.367  0.343
 1    나성범  NC  123  536  477  157  30  88  101  43  128  14  0.397  0.329
 2    박민우  NC  118  491  416  124   1  87   40  56   89  50  0.373  0.298
 3    손시헌  NC   97  361  307   90   5  39   39  34   53   2  0.331  0.293
 4    지석훈  NC  114  238  212   58   6  26   34  16   46   1  0.323  0.274
 5    이호준  NC  122  500  424  115  23  59   78  67  104   2  0.305  0.271
 6    권희동  NC  101  252  221   63   7  39   36  25   43   6  0.324  0.285
 7    모창민  NC  122  468  419  110  16  62   72  37   82  14  0.289  0.263
 8    이종욱  NC  124  495  438  126   6  73   79  40   60  15  0.313  0.288
 9    김준완  NC    6    5    4    2   0   1    0   1    1   1  0.667  0.500
 10   최재원  NC    2    2    1    0   0   1    0   1    1   0      -  0.000
 11   마낙길  NC    2    2    1    0   0   1    0   1    0   0  0.000  0.000
 12   조영훈  NC   92  124  111   29   6  15   22  10   26   1  0.288  0.261
 13   김태우  NC    4    5    5    1   0   0    0   0    3   0  0.500  0.200
 14  박명환*  NC    2    1    1    0   0   0    0   0    1   0      -  0.000
 15   조평호  NC    2    2    2    0   0   0    0   0    0   0  0.000  0.000
 16   강민국  NC    6    3    3    0   0   0    0   0    0   0  0.000  0.000
 17    허준  NC   28   36   29    5   0   2    1   5   10   0  0.263  0.172
 18   김성욱  NC   26   26   23    4   1   6    1   3    9   1  0.231  0.174
 19   노진혁  NC   25   16   16    3   1   3    2   0    7   0  0.250  0.188

       출루율    장타율    OPS   wOBA   WAR
 0   0.422  0.688  1.110  0.456  6.36
 1   0.400  0.597  0.997  0.424  5.94
 2   0.392  0.399  0.791  0.365  2.73
 3   0.368  0.414  0.782  0.349  1.52
 4   0.340  0.462  0.802  0.352  0.97
 5   0.371  0.481  0.852  0.369  0.88
 6   0.363  0.443  0.806  0.353  0.62
 7   0.320  0.413  0.733  0.319  0.17
 8   0.343  0.411  0.754  0.332  0.13
 9   0.600  0.500  1.100  0.509  0.11
 10  0.500  0.000  0.500  0.363  0.01
 11  0.500  0.000  0.500  0.363  0.01
 12  0.325  0.459  0.784  0.337 -0.02
 13  0.200  0.400  0.600  0.244 -0.03
 14  0.000  0.000  0.000  0.000 -0.03
 15  0.000  0.000  0.000  0.000 -0.07
 16  0.000  0.000  0.000  0.000 -0.10
 17  0.294  0.276  0.570  0.268 -0.11
 18  0.269  0.348  0.617  0.272 -0.15
 19  0.188  0.375  0.563  0.231 -0.18  ,
 '2015':     선수명  팀명   경기   타석   타수   안타  홈런   득점   타점   볼넷   삼진  도루  BABIP     타율  \
 0   테임즈  NC  142  595  472  180  47  130  140  103   91  40  0.390  0.381
 1   나성범  NC  144  622  564  184  28  112  135   33  127  23  0.374  0.326
 2   박민우  NC  141  617  520  158   3  111   47   73  108  46  0.373  0.304
 3   이호준  NC  131  518  449  132  24   48  110   61  102   0  0.332  0.294
 4   김종호  NC  133  486  424  125   4   90   36   44   65  41  0.338  0.295
 5   조영훈  NC  103  146  124   35   8   20   35   19   36   3  0.329  0.282
 6   손시헌  NC  140  508  440  108  13   56   58   36   66   3  0.260  0.245
 7   이종욱  NC  125  504  440  118   5   63   52   54   78  17  0.315  0.268
 8   모창민  NC  103  239  214   62   6   23   35   18   52   5  0.352  0.290
 9   지석훈  NC  137  466  415  111  11   53   46   23   85   4  0.311  0.267
 10  용덕한  NC   50   49   42   12   0    4    5    5    8   2  0.353  0.286
 11  최재원  NC  114  102   85   21   2   31   13   10   29  14  0.352  0.247
 12  박정준  NC   19   24   21    8   0    2    2    0    5   0  0.500  0.381
 13  김태군  NC  144  474  421  107   6   45   52   25   77   1  0.293  0.254
 14  조평호  NC   22   22   22    8   1    4    3    0    6   0  0.467  0.364
 15  이창섭  NC   15    8    5    0   0    0    0    3    3   0  0.000  0.000
 16  김준완  NC   30   54   44   10   0   12    2   10   10   2  0.294  0.227
 17  강구성  NC    4    5    5    1   0    0    0    0    0   0  0.200  0.200
 18  강민국  NC    1    2    2    0   0    0    0    0    1   0  0.000  0.000
 19  김태진  NC    1    3    3    0   0    0    0    0    0   0  0.000  0.000

       출루율    장타율    OPS   wOBA    WAR
 0   0.497  0.790  1.287  0.520  11.73
 1   0.373  0.553  0.926  0.390   4.46
 2   0.399  0.404  0.803  0.364   3.52
 3   0.381  0.510  0.891  0.381   2.19
 4   0.364  0.394  0.758  0.340   1.03
 5   0.372  0.540  0.912  0.389   1.00
 6   0.319  0.398  0.717  0.316   0.85
 7   0.351  0.368  0.719  0.322   0.84
 8   0.340  0.439  0.779  0.340   0.76
 9   0.328  0.383  0.711  0.317   0.51
 10  0.375  0.310  0.685  0.326   0.44
 11  0.366  0.412  0.778  0.350   0.30
 12  0.458  0.476  0.934  0.417   0.25
 13  0.307  0.354  0.661  0.294   0.25
 14  0.364  0.591  0.955  0.401   0.18
 15  0.375  0.000  0.375  0.286  -0.01
 16  0.370  0.227  0.597  0.308  -0.04
 17  0.200  0.400  0.600  0.242  -0.04
 18  0.000  0.000  0.000  0.000  -0.06
 19  0.000  0.000  0.000  0.000  -0.09  }

## 엑셀 파일 쓰기

하나의 엑셀 파일에 여러 시트로 저장하기

In [6]:
NC시즌 = pd.ExcelWriter('NC Dinos.xlsx')

for 시즌, 프레임 in 프레임목록.items():
    프레임.to_excel(NC시즌, str(시즌))

NC시즌.save()

# 한국수출입은행 (공공데이터) 엑셀 파일 처리

In [7]:
경로 = '../data/koreaexim/international/Global+Market+Daily+Table%28%EA%B0%92%EB%B3%B5%EC%82%AC%29_0803.xls'

파일 경로에 포함된 이상한 기호들의 정체

In [8]:
from urllib.parse import unquote_plus as url디코드
url디코드(경로)

'../data/koreaexim/international/Global Market Daily Table(값복사)_0803.xls'

액셀 파일을 읽어보니 위쪽 빈줄이 많다.

In [9]:
pd.read_excel(경로)

                                              Global Market Daily Update  \
NaN NaN                                                              NaN
    NaN                                                              NaN
    NaN                                                           Equity
    NaN                                                              NaN
    MXWD Index                                             MSCI AC World
    SPX Index                                                    S&P 500
    SX5E Index                                             Euro Stoxx 50
    DAX Index                                                        DAX
    NKY Index                                                 Nikkei 225
    SHCOMP Index                                                      상해
    NaN                                                              NaN
    NaN                                                     Fixed Income
    NaN                                                              NaN
    USGG10YR Index                                               UST 10Y
    USGG2YR Index                                                 UST 2Y
    USGG10YR-USGG2YR                                      Spread(10Y-2Y)
    GECU10YR Index                                              Bund 10Y
    GECU2YR Index                                                Bund 2Y
    GECU10YR - GECU2YR                                    Spread(10Y-2Y)
    NaN                                                              NaN
    NaN                                                               FX
    NaN                                                              NaN
    DXY Curncy                                              Dollar Index
    EURUSD Curncy                                                    EUR
    GBPUSD Curncy                                                    GBP
    USDJPY Curncy                                                    JPY
    AUDUSD Curncy                                                    AUD
    NaN                   * D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동
    NaN                                                              NaN
    NaN                                                       Commodity
    NaN                                                              NaN
    CLA COMDTY                                                       WTI
    GCA COMDTY                                                      Gold
    C A COMDTY                                                      Corn
    NaN                                                              NaN
    NaN                                                              NaN
    NaN                                                              CDS
    NaN                                                              NaN
    CCHIN1U5 CBIT CURNCY                                           China
    CINO1U5 CBIT CURNCY                                        Indonesia
    CMLAY1U5 CBIT CURNCY                                        Malaysia
    CTHAI1U5 CBIT CURNCY                                        Thailand
    cruss1u5 cbit curncy                                          Russia
    CSOAF1U5 CBIT CURNCY                                    South Africa
    CTURK1U5 CBIT CURNCY                                          Turkey
    CBRZ1U5 CBIT CURNCY                                           Brazil
    CKREA1U5 CBIT CURNCY                                           Korea
    NaN                                                              NaN
    NaN                                                              NaN
    NaN                                                            Japan
    NaN                                                            Italy
    NaN                                                            Spain

                             Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  \
NaN NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                      Last Price         D-1         D-7         MTD
    MXWD Index                   425.32 -0.00342097   0.0141638 -0.00342097
    SPX Index                   2098.04 -0.00275686   0.0147028 -0.00275686
    SX5E Index                   3635.4  0.00963982   0.0348126  0.00963982
    DAX Index                   11443.7   0.0119135   0.0350313   0.0119135
    NKY Index                   20548.1 -0.00180372  0.00973017 -0.00180372
    SHCOMP Index                3622.91  -0.0111417  -0.0275537  -0.0111417
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                   Last Price(%)         D-1         D-7         MTD
    USGG10YR Index                2.148          -3       -6.95       -3.21
    USGG2YR Index                0.6646           0        1.51         0.4
    USGG10YR-USGG2YR             1.4834          -3       -8.46       -3.61
    GECU10YR Index                0.628          -1        -6.3        -1.6
    GECU2YR Index                -0.244           0        -1.8        -0.9
    GECU10YR - GECU2YR            0.872          -1        -4.5        -0.7
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                      Last Price         D-1         D-7         MTD
    DXY Curncy                   97.494  0.00162324   0.0102796  0.00162324
    EURUSD Curncy                 1.095 -0.00309541  -0.0124459 -0.00309541
    GBPUSD Curncy                1.5587 -0.00224043   0.0017996 -0.00224043
    USDJPY Curncy                124.03 -0.00112876  -0.0062888 -0.00112876
    AUDUSD Curncy                0.7286  -0.0030104   0.0023387  -0.0030104
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                      Last Price         D-1         D-7         MTD
    CLA COMDTY                    45.17  -0.0413837  -0.0468453  -0.0413837
    GCA COMDTY                   1089.4   -0.005205 -0.00683745   -0.005205
    C A COMDTY                    376.5   -0.012459  -0.0182529   -0.012459
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                             NaN         NaN         NaN         NaN
    NaN                      Last Price         D-1         D-7         MTD
    CCHIN1U5 CBIT CURNCY            101       0.831      -0.501       0.831
    CINO1U5 CBIT CURNCY         186.757       3.249       5.545       3.249
    CMLAY1U5 CBIT CURNCY        152.159       4.173      10.277       4.173
    CTHAI1U5 CBIT CURNCY            109           2           1           2
    cruss1u5 cbit curncy        345.773       6.039       3.628       6.039
    CSOAF1U5 CBIT CURNCY        219.178      -0.717      -0.887      -0.717
    CTURK1U5 CBIT CURNCY        236.839      -1.569       6.529      -1.569
    CBRZ1U5 CBIT CURNCY         292.362       4.642      -4.678       4.642
    CKREA1U5 CBIT CURNCY         54.165       0.331      -0.751       0.331
    NaN                             NaN         NaN         NaN         NaN
    NaN                      Last Price         D-1         D-7         MTD
    NaN                              40           0      -0.713           0
    NaN                         114.915      -0.611      -0.215      -0.611
    NaN                          94.888      -0.057       2.668      -0.057

                          Unnamed: 5       As of: 2014-10-20 00:00:00  \
NaN NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    MXWD Index           -0.00561115    0.0196586               442.7
    SPX Index              0.0150366    0.0190102             2130.82
    SX5E Index            -0.0214978     0.155405             3828.78
    DAX Index             -0.0437581     0.167066             12374.7
    NKY Index              0.0572691      0.17749               20868
    SHCOMP Index           -0.062378     0.120021             5166.35
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    USGG10YR Index             30.91        -2.32              2.6198
    USGG2YR Index              18.84         0.01              0.7393
    USGG10YR-USGG2YR           12.07        -2.33              2.0562
    GECU10YR Index              43.4          8.7               1.167
    GECU2YR Index                1.3        -13.4               0.027
    GECU10YR - GECU2YR          42.1         22.1               1.157
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    DXY Curncy            0.00982961    0.0800386              100.33
    EURUSD Curncy        -0.00173215   -0.0948917              1.3422
    GBPUSD Curncy          0.0447051  0.000641972              1.6886
    USDJPY Curncy         -0.0407966   -0.0342659              102.03
    AUDUSD Curncy         -0.0454605    -0.108746              0.9378
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    CLA COMDTY             -0.154278    -0.158845               93.38
    GCA COMDTY            -0.0947316   -0.0805975                1321
    C A COMDTY            -0.0828258   -0.0720887              451.75
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    CCHIN1U5 CBIT CURNCY       8.333       14.013             104.336
    CINO1U5 CBIT CURNCY       30.208       26.445             183.748
    CMLAY1U5 CBIT CURNCY      24.706       45.332             151.325
    CTHAI1U5 CBIT CURNCY         5.5            6             119.511
    cruss1u5 cbit curncy     -27.167     -126.441             628.765
    CSOAF1U5 CBIT CURNCY      11.862       29.295             240.794
    CTURK1U5 CBIT CURNCY      20.735       60.005             238.408
    CBRZ1U5 CBIT CURNCY       27.912       95.564             306.576
    CKREA1U5 CBIT CURNCY        2.08       -0.326              67.609
    NaN                          NaN          NaN                 NaN
    NaN                          QTD          YTD             Yr High
    NaN                        4.511        -27.5              73.833
    NaN                        6.397      -24.382              160.16
    NaN                        9.649       -2.852             130.438

                         2014-10-18 00:00:00 Unnamed: 9  2015-08-03 00:00:00
NaN NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low   Low-high                  NaN
    MXWD Index                        392.13        NaN                  NaN
    SPX Index                        1862.49        NaN                  NaN
    SX5E Index                       2874.65        NaN                  NaN
    DAX Index                        8571.95        NaN                  NaN
    NKY Index                        14532.5        NaN                  NaN
    SHCOMP Index                     2187.67        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low        NaN                  NaN
    USGG10YR Index                    1.6407        NaN                  NaN
    USGG2YR Index                     0.3076        NaN                  NaN
    USGG10YR-USGG2YR                  1.1919        NaN                  NaN
    GECU10YR Index                     0.075        NaN                  NaN
    GECU2YR Index                     -0.283        NaN                  NaN
    GECU10YR - GECU2YR                 0.342        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low        NaN                  NaN
    DXY Curncy                        81.328        NaN                  NaN
    EURUSD Curncy                     1.0496        NaN                  NaN
    GBPUSD Curncy                     1.4632        NaN                  NaN
    USDJPY Curncy                    125.612        NaN                  NaN
    AUDUSD Curncy                     0.7269        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low        NaN                  NaN
    CLA COMDTY                         47.12        NaN                  NaN
    GCA COMDTY                          1086        NaN                  NaN
    C A COMDTY                         363.5        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low        NaN                  NaN
    CCHIN1U5 CBIT CURNCY              66.838        NaN                  NaN
    CINO1U5 CBIT CURNCY              127.162        NaN                  NaN
    CMLAY1U5 CBIT CURNCY              73.677        NaN                  NaN
    CTHAI1U5 CBIT CURNCY               80.84        NaN                  NaN
    cruss1u5 cbit curncy             221.835        NaN                  NaN
    CSOAF1U5 CBIT CURNCY                 159        NaN                  NaN
    CTURK1U5 CBIT CURNCY                 156        NaN                  NaN
    CBRZ1U5 CBIT CURNCY               123.25        NaN                  NaN
    CKREA1U5 CBIT CURNCY              45.491        NaN                  NaN
    NaN                                  NaN        NaN                  NaN
    NaN                               Yr Low        NaN                  NaN
    NaN                               31.335        NaN                  NaN
    NaN                                84.16        NaN                  NaN
    NaN                               56.493        NaN                  NaN

위의 3줄은 건너뛰기로 한다.

In [10]:
pd.read_excel(경로, skiprows=3)

,Unnamed: 0,Unnamed: 1,Equity,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,Low-high,NaN
1,NaN,MXWD Index,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13,NaN,NaN
2,NaN,SPX Index,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49,NaN,NaN
3,NaN,SX5E Index,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65,NaN,NaN
4,NaN,DAX Index,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95,NaN,NaN
5,NaN,NKY Index,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5,NaN,NaN
6,NaN,SHCOMP Index,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,Fixed Income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,Last Price(%),D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,NaN,NaN
10,NaN,USGG10YR Index,UST 10Y,2.148,-3,-6.95,-3.21,30.91,-2.32,2.6198,1.6407,NaN,NaN
11,NaN,USGG2YR Index,UST 2Y,0.6646,0,1.51,0.4,18.84,0.01,0.7393,0.3076,NaN,NaN
12,NaN,USGG10YR-USGG2YR,Spread(10Y-2Y),1.4834,-3,-8.46,-3.61,12.07,-2.33,2.0562,1.1919,NaN,NaN
13,NaN,GECU10YR Index,Bund 10Y,0.628,-1,-6.3,-1.6,43.4,8.7,1.167,0.075,NaN,NaN
14,NaN,GECU2YR Index,Bund 2Y,-0.244,0,-1.8,-0.9,1.3,-13.4,0.027,-0.283,NaN,NaN
15,NaN,GECU10YR - GECU2YR,Spread(10Y-2Y),0.872,-1,-4.5,-0.7,42.1,22.1,1.157,0.342,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,FX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,NaN,NaN
19,NaN,DXY Curncy,Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328,NaN,NaN
20,NaN,EURUSD Curncy,EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496,NaN,NaN
21,NaN,GBPUSD Curncy,GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632,NaN,NaN
22,NaN,USDJPY Curncy,JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612,NaN,NaN
23,NaN,AUDUSD Curncy,AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269,NaN,NaN
24,NaN,NaN,"* D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,Commodity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,NaN,NaN
28,NaN,CLA COMDTY,WTI,45.17,-0.0413837,-0.0468453,-0.0413837,-0.154278,-0.158845,93.38,47.12,NaN,NaN
29,NaN,GCA COMDTY,Gold,1089.4,-0.005205,-0.00683745,-0.005205,-0.0947316,-0.0805975,1321,1086,NaN,NaN
30,NaN,C A COMDTY,Corn,376.5,-0.012459,-0.0182529,-0.012459,-0.0828258,-0.0720887,451.75,363.5,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,NaN,NaN
35,NaN,CCHIN1U5 CBIT CURNCY,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838,NaN,NaN
36,NaN,CINO1U5 CBIT CURNCY,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162,NaN,NaN
37,NaN,CMLAY1U5 CBIT CURNCY,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677,NaN,NaN
38,NaN,CTHAI1U5 CBIT CURNCY,Thailand,109,2,1,2,5.5,6,119.511,80.84,NaN,NaN
39,NaN,cruss1u5 cbit curncy,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835,NaN,NaN
40,NaN,CSOAF1U5 CBIT CURNCY,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159,NaN,NaN
41,NaN,CTURK1U5 CBIT CURNCY,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156,NaN,NaN
42,NaN,CBRZ1U5 CBIT CURNCY,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25,NaN,NaN
43,NaN,CKREA1U5 CBIT CURNCY,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low,NaN,NaN
46,NaN,NaN,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335,NaN,NaN
47,NaN,NaN,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16,NaN,NaN
48,NaN,NaN,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493,NaN,NaN

열은 액셀의 C열부터 K열까지 가져오도록 한다.

In [11]:
pd.read_excel(경로, skiprows=3, parse_cols="C:K")

,Equity,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
1,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13
2,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49
3,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65
4,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95
5,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5
6,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Fixed Income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Last Price(%),D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
10,UST 10Y,2.148,-3,-6.95,-3.21,30.91,-2.32,2.6198,1.6407
11,UST 2Y,0.6646,0,1.51,0.4,18.84,0.01,0.7393,0.3076
12,Spread(10Y-2Y),1.4834,-3,-8.46,-3.61,12.07,-2.33,2.0562,1.1919
13,Bund 10Y,0.628,-1,-6.3,-1.6,43.4,8.7,1.167,0.075
14,Bund 2Y,-0.244,0,-1.8,-0.9,1.3,-13.4,0.027,-0.283
15,Spread(10Y-2Y),0.872,-1,-4.5,-0.7,42.1,22.1,1.157,0.342
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,FX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
19,Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328
20,EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496
21,GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632
22,JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612
23,AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269
24,"* D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Commodity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
28,WTI,45.17,-0.0413837,-0.0468453,-0.0413837,-0.154278,-0.158845,93.38,47.12
29,Gold,1089.4,-0.005205,-0.00683745,-0.005205,-0.0947316,-0.0805975,1321,1086
30,Corn,376.5,-0.012459,-0.0182529,-0.012459,-0.0828258,-0.0720887,451.75,363.5
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
35,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
36,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
37,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
38,Thailand,109,2,1,2,5.5,6,119.511,80.84
39,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
40,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
41,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
42,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
43,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
46,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
47,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
48,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493

표가 여러 개라 열제목은 일단 없음으로 설정해야겠다.

In [12]:
국제0803 = pd.read_excel(경로, skiprows=3, parse_cols="C:K", header=None)
국제0803

,0,1,2,3,4,5,6,7,8
0,Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
2,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13
3,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49
4,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65
5,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95
6,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5
7,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Fixed Income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Last Price(%),D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
11,UST 10Y,2.148,-3,-6.95,-3.21,30.91,-2.32,2.6198,1.6407
12,UST 2Y,0.6646,0,1.51,0.4,18.84,0.01,0.7393,0.3076
13,Spread(10Y-2Y),1.4834,-3,-8.46,-3.61,12.07,-2.33,2.0562,1.1919
14,Bund 10Y,0.628,-1,-6.3,-1.6,43.4,8.7,1.167,0.075
15,Bund 2Y,-0.244,0,-1.8,-0.9,1.3,-13.4,0.027,-0.283
16,Spread(10Y-2Y),0.872,-1,-4.5,-0.7,42.1,22.1,1.157,0.342
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,FX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
20,Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328
21,EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496
22,GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632
23,JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612
24,AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269
25,"* D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Commodity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
29,WTI,45.17,-0.0413837,-0.0468453,-0.0413837,-0.154278,-0.158845,93.38,47.12
30,Gold,1089.4,-0.005205,-0.00683745,-0.005205,-0.0947316,-0.0805975,1321,1086
31,Corn,376.5,-0.012459,-0.0182529,-0.012459,-0.0828258,-0.0720887,451.75,363.5
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
36,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
37,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
38,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
39,Thailand,109,2,1,2,5.5,6,119.511,80.84
40,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
41,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
42,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
43,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
44,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
47,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
48,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
49,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493

빈 줄은 삭제하자

In [13]:
국제0803 = 국제0803.dropna(how='all')
국제0803

,0,1,2,3,4,5,6,7,8
0,Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
2,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13
3,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49
4,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65
5,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95
6,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5
7,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67
9,Fixed Income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Last Price(%),D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
11,UST 10Y,2.148,-3,-6.95,-3.21,30.91,-2.32,2.6198,1.6407
12,UST 2Y,0.6646,0,1.51,0.4,18.84,0.01,0.7393,0.3076
13,Spread(10Y-2Y),1.4834,-3,-8.46,-3.61,12.07,-2.33,2.0562,1.1919
14,Bund 10Y,0.628,-1,-6.3,-1.6,43.4,8.7,1.167,0.075
15,Bund 2Y,-0.244,0,-1.8,-0.9,1.3,-13.4,0.027,-0.283
16,Spread(10Y-2Y),0.872,-1,-4.5,-0.7,42.1,22.1,1.157,0.342
18,FX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
20,Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328
21,EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496
22,GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632
23,JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612
24,AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269
25,"* D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Commodity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
29,WTI,45.17,-0.0413837,-0.0468453,-0.0413837,-0.154278,-0.158845,93.38,47.12
30,Gold,1089.4,-0.005205,-0.00683745,-0.005205,-0.0947316,-0.0805975,1321,1086
31,Corn,376.5,-0.012459,-0.0182529,-0.012459,-0.0828258,-0.0720887,451.75,363.5
34,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
36,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
37,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
38,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
39,Thailand,109,2,1,2,5.5,6,119.511,80.84
40,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
41,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
42,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
43,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
44,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
46,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
47,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
48,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
49,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493

빈 줄이 삭제되면서 색인 번호가 고르지 않아졌다.

In [14]:
try: 
    국제0803.ix[8] # KeyError
except KeyError:
    print('그런 색인 없어요!')

그런 색인 없어요!

색인을 재설정하자

In [15]:
국제0803 = 국제0803.reset_index(drop=True)
국제0803

,0,1,2,3,4,5,6,7,8
0,Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
2,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13
3,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49
4,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65
5,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95
6,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5
7,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67
8,Fixed Income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Last Price(%),D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
10,UST 10Y,2.148,-3,-6.95,-3.21,30.91,-2.32,2.6198,1.6407
11,UST 2Y,0.6646,0,1.51,0.4,18.84,0.01,0.7393,0.3076
12,Spread(10Y-2Y),1.4834,-3,-8.46,-3.61,12.07,-2.33,2.0562,1.1919
13,Bund 10Y,0.628,-1,-6.3,-1.6,43.4,8.7,1.167,0.075
14,Bund 2Y,-0.244,0,-1.8,-0.9,1.3,-13.4,0.027,-0.283
15,Spread(10Y-2Y),0.872,-1,-4.5,-0.7,42.1,22.1,1.157,0.342
16,FX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
18,Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328
19,EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496
20,GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632
21,JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612
22,AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269
23,"* D-1,D-7,MTD,QTD,YTD 변동분은 USD 대비 해당 통화 가치의 변동",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Commodity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
26,WTI,45.17,-0.0413837,-0.0468453,-0.0413837,-0.154278,-0.158845,93.38,47.12
27,Gold,1089.4,-0.005205,-0.00683745,-0.005205,-0.0947316,-0.0805975,1321,1086
28,Corn,376.5,-0.012459,-0.0182529,-0.012459,-0.0828258,-0.0720887,451.75,363.5
29,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
31,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
32,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
33,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
34,Thailand,109,2,1,2,5.5,6,119.511,80.84
35,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
36,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
37,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
38,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
39,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
40,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
41,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
42,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
43,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493

각 표를 각각의 데이터프레임으로 잘라내자

In [16]:
국제0803.iloc[0:8]

,0,1,2,3,4,5,6,7,8
0,Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
2,MSCI AC World,425.32,-0.00342097,0.0141638,-0.00342097,-0.00561115,0.0196586,442.7,392.13
3,S&P 500,2098.04,-0.00275686,0.0147028,-0.00275686,0.0150366,0.0190102,2130.82,1862.49
4,Euro Stoxx 50,3635.4,0.00963982,0.0348126,0.00963982,-0.0214978,0.155405,3828.78,2874.65
5,DAX,11443.7,0.0119135,0.0350313,0.0119135,-0.0437581,0.167066,12374.7,8571.95
6,Nikkei 225,20548.1,-0.00180372,0.00973017,-0.00180372,0.0572691,0.17749,20868,14532.5
7,상해,3622.91,-0.0111417,-0.0275537,-0.0111417,-0.062378,0.120021,5166.35,2187.67

범위 목록을 만들어서 한번에 처리하자

In [17]:
표정보목록 = [('equity', 0,8), 
          ('fixed income',8,18), 
          ('fx',16,22), 
          ('commodity',24,29), 
          ('cds',29,44)]

In [18]:
국제0803_표사전 = {}
for 표정보 in 표정보목록:
    제목, 시작, 종료 = 표정보
    국제0803_표사전[제목] = 국제0803.iloc[시작:종료]

In [19]:
국제0803_표사전['cds']

,0,1,2,3,4,5,6,7,8
29,CDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
31,China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
32,Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
33,Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
34,Thailand,109,2,1,2,5.5,6,119.511,80.84
35,Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
36,South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
37,Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
38,Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
39,Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
40,NaN,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
41,Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
42,Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
43,Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493

색인범위를 자동으로 구할 수도 있을까?

In [20]:
색인시작목록 = list(국제0803[국제0803.notnull().sum(1) == 1].index)
색인시작목록

[0, 8, 16, 23, 24, 29]

In [21]:
색인종료목록 = 색인시작목록[1:]
색인종료목록.append(len(국제0803))
색인종료목록

[8, 16, 23, 24, 29, 44]

제목 추출

In [22]:
제목목록 = [국제0803.iloc[i,0].lower() for i in 색인시작목록]
제목목록

['equity',
 'fixed income',
 'fx',
 '* d-1,d-7,mtd,qtd,ytd 변동분은 usd 대비 해당 통화 가치의 변동',
 'commodity ',
 'cds']

In [23]:
표정보목록 = list(zip(제목목록, 색인시작목록, 색인종료목록))
표정보목록

[('equity', 0, 8),
 ('fixed income', 8, 16),
 ('fx', 16, 23),
 ('* d-1,d-7,mtd,qtd,ytd 변동분은 usd 대비 해당 통화 가치의 변동', 23, 24),
 ('commodity ', 24, 29),
 ('cds', 29, 44)]

색인과 열제목 설정

NaN 색인 제거

## 모듈화

모듈 탐색 경로 설정

In [24]:
모듈경로 = os.path.abspath('../modules/')
sys.path.append(모듈경로)

모듈 가져오기

In [25]:
from koreaexim import 데이터프레임추출

In [26]:
표사전 = 데이터프레임추출('../data/koreaexim/international/Global+Market+Daily+Table%28%EA%B0%92%EB%B3%B5%EC%82%AC%29_0803.xls')

In [27]:
표사전['fx']

,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
FX,,,,,,,,
Dollar Index,97.494,0.00162324,0.0102796,0.00162324,0.00982961,0.0800386,100.33,81.328
EUR,1.095,-0.00309541,-0.0124459,-0.00309541,-0.00173215,-0.0948917,1.3422,1.0496
GBP,1.5587,-0.00224043,0.0017996,-0.00224043,0.0447051,0.000641972,1.6886,1.4632
JPY,124.03,-0.00112876,-0.0062888,-0.00112876,-0.0407966,-0.0342659,102.03,125.612
AUD,0.7286,-0.0030104,0.0023387,-0.0030104,-0.0454605,-0.108746,0.9378,0.7269

In [28]:
표사전['cds']

,Last Price,D-1,D-7,MTD,QTD,YTD,Yr High,Yr Low
CDS,,,,,,,,
China,101,0.831,-0.501,0.831,8.333,14.013,104.336,66.838
Indonesia,186.757,3.249,5.545,3.249,30.208,26.445,183.748,127.162
Malaysia,152.159,4.173,10.277,4.173,24.706,45.332,151.325,73.677
Thailand,109,2,1,2,5.5,6,119.511,80.84
Russia,345.773,6.039,3.628,6.039,-27.167,-126.441,628.765,221.835
South Africa,219.178,-0.717,-0.887,-0.717,11.862,29.295,240.794,159
Turkey,236.839,-1.569,6.529,-1.569,20.735,60.005,238.408,156
Brazil,292.362,4.642,-4.678,4.642,27.912,95.564,306.576,123.25
Korea,54.165,0.331,-0.751,0.331,2.08,-0.326,67.609,45.491
Japan,40,0,-0.713,0,4.511,-27.5,73.833,31.335
Italy,114.915,-0.611,-0.215,-0.611,6.397,-24.382,160.16,84.16
Spain,94.888,-0.057,2.668,-0.057,9.649,-2.852,130.438,56.493